import { Metadata } from "next";
import Link from "next/link";
import { Brain, Activity, Heart, Eye, Zap, ArrowRight, Code2, TrendingUp } from "lucide-react";

export const metadata: Metadata = {
  title: "Biosignals — PiEEG",
  description:
    "Learn about EEG, EMG, ECG, and EOG. Understand what biosignals are, how they're measured, and what you can do with them.",
};

const signals = [
  {
    id: "eeg",
    name: "EEG",
    fullName: "Electroencephalography",
    icon: Brain,
    tagline: "Brain electrical activity",
    description:
      "Measure voltage fluctuations from ionic currents in neurons. The foundation of brain-computer interfaces and neuroscience research.",
    frequency: "0.5–100 Hz",
    amplitude: "10–100 µV",
    gradient: "from-purple-500 to-pink-600",
    bgGradient: "from-purple-50 to-pink-50 dark:from-purple-950/30 dark:to-pink-950/30",
    applications: [
      "Sleep stage detection",
      "Seizure monitoring",
      "Brain-computer interfaces",
      "Cognitive state monitoring",
      "Meditation & focus tracking",
      "P300 speller systems"
    ],
    bands: [
      { name: "Delta (δ)", range: "0.5–4 Hz", state: "Deep sleep" },
      { name: "Theta (θ)", range: "4–8 Hz", state: "Drowsiness, meditation" },
      { name: "Alpha (α)", range: "8–13 Hz", state: "Relaxed, eyes closed" },
      { name: "Beta (β)", range: "13–30 Hz", state: "Alert, active thinking" },
      { name: "Gamma (γ)", range: "30–100 Hz", state: "Cognitive processing" }
    ],
    code: `from pieeg import PiEEG

# Initialize 8-channel EEG
eeg = PiEEG(channels=8, sample_rate=250)

# Stream real-time data
for sample in eeg.stream():
    # sample shape: (8, 250) - 8 channels @ 250 Hz
    alpha_power = eeg.band_power(sample, 8, 13)
    print(f"Alpha: {alpha_power:.2f} µV²")`
  },
  {
    id: "emg",
    name: "EMG",
    fullName: "Electromyography",
    icon: Activity,
    tagline: "Muscle electrical activity",
    description:
      "Capture electrical signals generated by muscle contractions. Perfect for prosthetic control, rehabilitation, and sports science.",
    frequency: "20–500 Hz",
    amplitude: "50–5000 µV",
    gradient: "from-cyan-500 to-blue-600",
    bgGradient: "from-cyan-50 to-blue-50 dark:from-cyan-950/30 dark:to-blue-950/30",
    applications: [
      "Prosthetic limb control",
      "Gesture recognition",
      "Rehabilitation monitoring",
      "Sports performance analysis",
      "Fatigue detection",
      "Gait analysis"
    ],
    bands: [
      { name: "Motor Unit Firing", range: "20–150 Hz", state: "Voluntary contraction" },
      { name: "High-Frequency", range: "150–500 Hz", state: "Force modulation" }
    ],
    code: `from pieeg import PiEEG

# Configure for EMG acquisition
emg = PiEEG(channels=4, sample_rate=1000)
emg.set_gain(24)  # Higher gain for muscle signals

# Detect muscle activation
for sample in emg.stream():
    rms = emg.rms(sample)
    if rms > threshold:
        print("Muscle activated!")`
  },
  {
    id: "ecg",
    name: "ECG",
    fullName: "Electrocardiography",
    icon: Heart,
    tagline: "Heart electrical activity",
    description:
      "Record the electrical activity of the heart. Monitor heart rate, detect arrhythmias, and analyze heart rate variability for stress assessment.",
    frequency: "0.5–150 Hz",
    amplitude: "0.5–4 mV",
    gradient: "from-red-500 to-orange-600",
    bgGradient: "from-red-50 to-orange-50 dark:from-red-950/30 dark:to-orange-950/30",
    applications: [
      "Heart rate monitoring",
      "Arrhythmia detection",
      "HRV analysis (stress)",
      "Fitness tracking",
      "Cardiac rehabilitation",
      "Biofeedback systems"
    ],
    bands: [
      { name: "P Wave", range: "Atrial depolarization", state: "~80 ms" },
      { name: "QRS Complex", range: "Ventricular depolarization", state: "~100 ms" },
      { name: "T Wave", range: "Ventricular repolarization", state: "~160 ms" }
    ],
    code: `from pieeg import PiEEG

# Single-channel ECG monitoring
ecg = PiEEG(channels=1, sample_rate=250)

# Detect heartbeats
for sample in ecg.stream():
    peaks = ecg.find_r_peaks(sample)
    hr = 60 * len(peaks) / duration
    print(f"Heart Rate: {hr:.1f} BPM")`
  },
  {
    id: "eog",
    name: "EOG",
    fullName: "Electrooculography",
    icon: Eye,
    tagline: "Eye movement tracking",
    description:
      "Track eye movements by measuring the corneo-retinal potential. Essential for sleep studies, HCI, and assistive technology.",
    frequency: "0.1–30 Hz",
    amplitude: "50–3500 µV",
    gradient: "from-green-500 to-teal-600",
    bgGradient: "from-green-50 to-teal-50 dark:from-green-950/30 dark:to-teal-950/30",
    applications: [
      "Sleep stage classification",
      "REM detection",
      "Gaze-based control",
      "Assistive communication",
      "Reading analysis",
      "Attention tracking"
    ],
    bands: [
      { name: "Horizontal", range: "Left-right eye movement", state: "Saccades, pursuit" },
      { name: "Vertical", range: "Up-down eye movement", state: "Blinks, vertical gaze" }
    ],
    code: `from pieeg import PiEEG

# Horizontal + vertical EOG
eog = PiEEG(channels=2, sample_rate=250)

# Track eye movements
for sample in eog.stream():
    h_eog, v_eog = sample
    if abs(h_eog) > threshold:
        direction = "Right" if h_eog > 0 else "Left"
        print(f"Saccade: {direction}")`
  }
];

const comparisonTable = [
  { signal: "EEG", source: "Brain neurons", amplitude: "10–100 µV", frequency: "0.5–100 Hz", electrodes: "Scalp" },
  { signal: "EMG", source: "Muscle fibers", amplitude: "50–5000 µV", frequency: "20–500 Hz", electrodes: "Skin over muscle" },
  { signal: "ECG", source: "Heart muscle", amplitude: "0.5–4 mV", frequency: "0.5–150 Hz", electrodes: "Chest/limbs" },
  { signal: "EOG", source: "Eye cornea-retina", amplitude: "50–3500 µV", frequency: "0.1–30 Hz", electrodes: "Near eyes" }
];

export default function SignalsPage() {
  return (
    <main className="flex-1">
      {/* Hero Section */}
      <section className="relative overflow-hidden border-b border-zinc-200 dark:border-zinc-800 bg-gradient-to-b from-zinc-50 to-white dark:from-zinc-900 dark:to-zinc-950">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 sm:py-24">
          <div className="text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-purple-200 dark:border-purple-800 bg-purple-50 dark:bg-purple-950/50 mb-6">
              <Zap className="w-4 h-4 text-purple-600 dark:text-purple-400" />
              <span className="text-xs font-semibold uppercase tracking-wider text-purple-600 dark:text-purple-400">
                Biosignal Education
              </span>
            </div>
            
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
              Your body speaks
              <br />
              <span className="bg-gradient-to-r from-purple-500 via-pink-600 to-red-600 dark:from-purple-400 dark:via-pink-500 dark:to-red-500 bg-clip-text text-transparent">
                in electrical signals
              </span>
            </h1>
            
            <p className="text-lg sm:text-xl text-zinc-600 dark:text-zinc-400 mb-8">
              Every thought, movement, and heartbeat generates electrical activity. Learn how to measure, analyze, and harness these biosignals.
            </p>

            <Link
              href="#eeg"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-gradient-to-r from-purple-500 to-pink-600 hover:from-purple-600 hover:to-pink-700 text-white font-semibold shadow-lg shadow-purple-500/30 transition-all"
            >
              Explore Signals
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Signal Deep Dives */}
      {signals.map((signal, idx) => {
        const Icon = signal.icon;
        return (
          <section
            key={signal.id}
            id={signal.id}
            className={`py-20 sm:py-24 ${idx % 2 === 0 ? 'bg-white dark:bg-zinc-950' : 'bg-zinc-50 dark:bg-zinc-900'}`}
          >
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="grid lg:grid-cols-2 gap-12 items-start">
                {/* Content */}
                <div className={idx % 2 === 1 ? 'lg:order-2' : ''}>
                  <div className="flex items-center gap-3 mb-6">
                    <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${signal.gradient} flex items-center justify-center text-white shadow-lg`}>
                      <Icon className="w-7 h-7" />
                    </div>
                    <div>
                      <div className="text-3xl font-bold">{signal.name}</div>
                      <div className="text-sm text-zinc-600 dark:text-zinc-400">{signal.fullName}</div>
                    </div>
                  </div>

                  <div className={`inline-block px-4 py-2 rounded-lg bg-gradient-to-r ${signal.gradient} text-white font-semibold mb-6`}>
                    {signal.tagline}
                  </div>

                  <p className="text-lg text-zinc-700 dark:text-zinc-300 mb-8 leading-relaxed">
                    {signal.description}
                  </p>

                  {/* Technical Specs */}
                  <div className="grid grid-cols-2 gap-4 mb-8 p-6 rounded-xl bg-gradient-to-br ${signal.bgGradient} border border-zinc-200 dark:border-zinc-800">
                    <div>
                      <div className="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400 mb-1">
                        Frequency Range
                      </div>
                      <div className="font-bold text-xl text-zinc-900 dark:text-zinc-100">
                        {signal.frequency}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400 mb-1">
                        Typical Amplitude
                      </div>
                      <div className="font-bold text-xl text-zinc-900 dark:text-zinc-100">
                        {signal.amplitude}
                      </div>
                    </div>
                  </div>

                  {/* Bands/Components */}
                  <div className="mb-8">
                    <h3 className="font-bold text-lg mb-4">
                      {signal.id === 'ecg' ? 'ECG Components' : signal.id === 'eog' ? 'EOG Channels' : 'Frequency Bands'}
                    </h3>
                    <div className="space-y-3">
                      {signal.bands.map((band, i) => (
                        <div
                          key={i}
                          className="flex items-center justify-between p-4 rounded-lg bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800"
                        >
                          <div>
                            <div className="font-semibold">{band.name}</div>
                            <div className="text-sm text-zinc-600 dark:text-zinc-400">{band.range}</div>
                          </div>
                          <div className="text-sm font-medium text-zinc-500">
                            {band.state}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Applications */}
                  <div>
                    <h3 className="font-bold text-lg mb-4">Applications</h3>
                    <div className="grid grid-cols-2 gap-2">
                      {signal.applications.map((app, i) => (
                        <div
                          key={i}
                          className="flex items-start gap-2 text-sm"
                        >
                          <TrendingUp className={`w-4 h-4 flex-shrink-0 mt-0.5 bg-gradient-to-r ${signal.gradient} bg-clip-text text-transparent`} />
                          <span className="text-zinc-700 dark:text-zinc-300">{app}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Code Example */}
                <div className={idx % 2 === 1 ? 'lg:order-1' : ''}>
                  <div className="sticky top-24">
                    <div className="mb-4 flex items-center gap-2">
                      <Code2 className="w-5 h-5 text-zinc-600 dark:text-zinc-400" />
                      <h3 className="font-bold text-lg">Quick Example</h3>
                    </div>
                    <div className="rounded-xl overflow-hidden border border-zinc-200 dark:border-zinc-800 shadow-xl">
                      {/* Terminal header */}
                      <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900">
                        <div className="flex items-center gap-2">
                          <div className="flex gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-red-400"></div>
                            <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
                            <div className="w-3 h-3 rounded-full bg-green-400"></div>
                          </div>
                          <span className="text-xs text-zinc-500 dark:text-zinc-400 ml-2">
                            {signal.id}_example.py
                          </span>
                        </div>
                      </div>
                      
                      {/* Code content */}
                      <div className="p-6 bg-zinc-900 dark:bg-zinc-950 overflow-x-auto">
                        <pre className="text-sm leading-relaxed">
                          <code className="text-zinc-100 font-mono whitespace-pre">
                            {signal.code}
                          </code>
                        </pre>
                      </div>
                    </div>

                    <div className="mt-6 p-4 rounded-lg bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800">
                      <div className="flex gap-3">
                        <div className={`w-8 h-8 rounded-lg bg-gradient-to-br ${signal.gradient} flex items-center justify-center text-white flex-shrink-0`}>
                          <Zap className="w-4 h-4" />
                        </div>
                        <div className="text-sm">
                          <div className="font-semibold mb-1">Try it yourself</div>
                          <div className="text-zinc-600 dark:text-zinc-400">
                            All PiEEG devices support {signal.name} acquisition out of the box. Check the docs for advanced filtering and processing.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        );
      })}

      {/* Comparison Table */}
      <section className="py-20 sm:py-24 bg-white dark:bg-zinc-950 border-t border-zinc-200 dark:border-zinc-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">
              Signal Comparison
            </h2>
            <p className="text-lg text-zinc-600 dark:text-zinc-400">
              Quick reference for all biosignal types
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full border border-zinc-200 dark:border-zinc-800 rounded-lg overflow-hidden">
              <thead>
                <tr className="bg-zinc-50 dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-800">
                  <th className="px-6 py-4 text-left font-bold">Signal</th>
                  <th className="px-6 py-4 text-left font-bold">Source</th>
                  <th className="px-6 py-4 text-left font-bold">Amplitude</th>
                  <th className="px-6 py-4 text-left font-bold">Frequency</th>
                  <th className="px-6 py-4 text-left font-bold">Electrode Placement</th>
                </tr>
              </thead>
              <tbody>
                {comparisonTable.map((row, idx) => (
                  <tr
                    key={row.signal}
                    className={`border-b border-zinc-200 dark:border-zinc-800 ${
                      idx % 2 === 0 ? 'bg-white dark:bg-zinc-950' : 'bg-zinc-50 dark:bg-zinc-900'
                    }`}
                  >
                    <td className="px-6 py-4 font-bold">{row.signal}</td>
                    <td className="px-6 py-4 text-zinc-600 dark:text-zinc-400">{row.source}</td>
                    <td className="px-6 py-4 font-mono text-sm">{row.amplitude}</td>
                    <td className="px-6 py-4 font-mono text-sm">{row.frequency}</td>
                    <td className="px-6 py-4 text-zinc-600 dark:text-zinc-400">{row.electrodes}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-gradient-to-br from-purple-500 via-pink-600 to-red-600 text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">
            Ready to measure your first biosignal?
          </h2>
          <p className="text-lg text-purple-50 mb-8 max-w-2xl mx-auto">
            Get started with PiEEG and start streaming EEG, EMG, ECG, or EOG in under 60 seconds.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/products"
              className="inline-flex items-center gap-2 px-8 py-4 rounded-lg bg-white text-pink-600 hover:bg-zinc-100 font-bold shadow-xl transition-all"
            >
              Browse Hardware
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link
              href="/docs"
              className="inline-flex items-center gap-2 px-8 py-4 rounded-lg border-2 border-white hover:bg-white/10 font-bold transition-all"
            >
              Read the Docs
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
